///////////////////////////////////////////////////////////
//  BaseController.cs
//  Implementation of the Class BaseController
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:01
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace PredatoryPlantsOnlineStore {
	public class BaseController {

		private DBController Data;

		public BaseController(){

		}

		~BaseController(){

		}

		public void Action(){

		}

		public void RedirectToAction(){

		}

	}//end BaseController

}//end namespace PredatoryPlantsOnlineStore