///////////////////////////////////////////////////////////
//  Cart.cs
//  Implementation of the Class Cart
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:02
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using PredatoryPlantsOnlineStore;
namespace PredatoryPlantsOnlineStore {
	public class Cart {

		private string description;
		private List<PredatoryPlant> plants_list;
		public PredatoryPlantsOnlineStore.User m_User;
		public PredatoryPlantsOnlineStore.PredatoryPlant m_PredatoryPlant;

		public Cart(){

		}

		~Cart(){

		}

		public int CalculatePrice(){

			return 0;
		}

		public void Clear(){

		}

		public int GetCountOfPlants(){

			return 0;
		}

		public string GetDescription(){

			return "";
		}

		public PredatoryPlant PredatoryPlant{
			get;
			set;
		}

		/// 
		/// <param name="descr"></param>
		public void SetDescription(string descr){

		}

		public User User{
			get;
			set;
		}

	}//end Cart

}//end namespace PredatoryPlantsOnlineStore