///////////////////////////////////////////////////////////
//  DBController.cs
//  Implementation of the Class DBController
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:01
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using PredatoryPlantsOnlineStore;
namespace PredatoryPlantsOnlineStore {
	public class DBController : IDBConnects {

		private int IDconnect;

		public DBController(){

		}

		~DBController(){

		}

		/// 
		/// <param name="entity"></param>
		public void AddEntity(object entity){

		}

		/// 
		/// <param name="entity"></param>
		public void DeleteEntity(object entity){

		}

		/// 
		/// <param name="entity"></param>
		public void EditEntity(object entity){

		}

		/// 
		/// <param name="type"></param>
		public Object GetAll(string type){

			return null;
		}

		/// 
		/// <param name="type"></param>
		public Object GetEntity(string type){

			return null;
		}

	}//end DBController

}//end namespace PredatoryPlantsOnlineStore