///////////////////////////////////////////////////////////
//  Director.cs
//  Implementation of the Class Director
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:02
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using PredatoryPlantsOnlineStore;
namespace PredatoryPlantsOnlineStore {
	public class Director : User {

		public Director(){

		}

		~Director(){

		}

		/// 
		/// <param name="date"></param>
		public Object GetConsumptionReport(DateTime date){

			return null;
		}

		/// 
		/// <param name="date"></param>
		public Object GetIncomeReport(DateTime date){

			return null;
		}

		/// 
		/// <param name="date"></param>
		public Object GetOrdersReport(DateTime date){

			return null;
		}

		/// 
		/// <param name="date"></param>
		public Object GetUniqueCustomersReport(DateTime date){

			return null;
		}

		public void SignOut(){

		}

	}//end Director

}//end namespace PredatoryPlantsOnlineStore