///////////////////////////////////////////////////////////
//  Guest.cs
//  Implementation of the Class Guest
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:02
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace PredatoryPlantsOnlineStore {
	public class Guest {

		public Guest(){

		}

		~Guest(){

		}

		/// 
		/// <param name="email"></param>
		/// <param name="pass_hash"></param>
		public bool SignIn(string email, string pass_hash){

			return false;
		}

		/// 
		/// <param name="email"></param>
		/// <param name="pass_hash"></param>
		public void SignUp(string email, string pass_hash){

		}

		public void ViewListCatalogue(){

		}

		/// 
		/// <param name="id_product"></param>
		public void ViewPredatoryPlantInfo(int id_product){

		}

	}//end Guest

}//end namespace PredatoryPlantsOnlineStore