///////////////////////////////////////////////////////////
//  GuestController.cs
//  Implementation of the Class GuestController
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:01
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using PredatoryPlantsOnlineStore;
namespace PredatoryPlantsOnlineStore {
	public class GuestController : BaseController {

		public GuestController(){

		}

		~GuestController(){

		}

		/// 
		/// <param name="email"></param>
		/// <param name="pass_hash"></param>
		public bool SignIn(string email, string pass_hash){

			return false;
		}

		/// 
		/// <param name="email"></param>
		/// <param name="pass_hash"></param>
		public void SignUp(string email, string pass_hash){

		}

		public void ViewListCatalogue(){

		}

		/// 
		/// <param name="id_product"></param>
		public void ViewPredatoryPlantInfo(int id_product){

		}

	}//end GuestController

}//end namespace PredatoryPlantsOnlineStore