///////////////////////////////////////////////////////////
//  IDBConnects.cs
//  Implementation of the Interface IDBConnects
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:01
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using PredatoryPlantsOnlineStore;
namespace PredatoryPlantsOnlineStore {
	public interface IDBConnects  {

		/// 
		/// <param name="entity"></param>
		void AddEntity(object entity);

		/// 
		/// <param name="entity"></param>
		void DeleteEntity(object entity);

		/// 
		/// <param name="entity"></param>
		void EditEntity(object entity);

		/// 
		/// <param name="type"></param>
		Object GetAll(string type);

		/// 
		/// <param name="type"></param>
		Object GetEntity(string type);
	}//end IDBConnects

}//end namespace PredatoryPlantsOnlineStore