///////////////////////////////////////////////////////////
//  Manager.cs
//  Implementation of the Class Manager
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:02
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using PredatoryPlantsOnlineStore;
namespace PredatoryPlantsOnlineStore {
	public class Manager : User {

		public Manager(){

		}

		~Manager(){

		}

		/// 
		/// <param name="elem"></param>
		public void AddElementToStorage(Object elem){

		}

		public void EditCatalogue(){

		}

		/// 
		/// <param name="name"></param>
		public Object FindElementInStorage(string name){

			return null;
		}

		/// 
		/// <param name="id_order"></param>
		public void FindInformationAboutOrder(int id_order){

		}

		public void GetUnprocessedOrders(){

		}

		/// 
		/// <param name="name"></param>
		/// <param name="info"></param>
		public void RegisterDelivery(string name, string info){

		}

		public void SignOut(){

		}

	}//end Manager

}//end namespace PredatoryPlantsOnlineStore