///////////////////////////////////////////////////////////
//  Order.cs
//  Implementation of the Class Order
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:03
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace PredatoryPlantsOnlineStore {
	public class Order {

		private DateTime date_sales;
		private int id_order;
		private int id_transaction;
		private int id_user;
		private int price;

		public Order(){

		}

		~Order(){

		}

		/// 
		/// <param name="plant"></param>
		public void AddPlantToCart(PredatoryPlant plant){

		}

		public void CalculatePrice(){

		}

	}//end Order

}//end namespace PredatoryPlantsOnlineStore