///////////////////////////////////////////////////////////
//  PredatoryPlant.cs
//  Implementation of the Class PredatoryPlant
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:02
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace PredatoryPlantsOnlineStore {
	public class PredatoryPlant {

		private int id_plant;
		private string information;
		private string name;
		private DateTime PlantedDate;
		private int price;

		public PredatoryPlant(){

		}

		~PredatoryPlant(){

		}

		public int GetPlantID(){

			return 0;
		}

		public string GetPlantInfo(){

			return "";
		}

		public int GetPlantPrice(){

			return 0;
		}

	}//end PredatoryPlant

}//end namespace PredatoryPlantsOnlineStore