///////////////////////////////////////////////////////////
//  Provider.cs
//  Implementation of the Class Provider
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:03
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace PredatoryPlantsOnlineStore {
	public class Provider {

		public Provider(){

		}

		~Provider(){

		}

		/// 
		/// <param name="obj"></param>
		public bool ProvideFlowerInfo(PredatoryPlant obj){

			return false;
		}

	}//end Provider

}//end namespace PredatoryPlantsOnlineStore