///////////////////////////////////////////////////////////
//  ProviderController.cs
//  Implementation of the Class ProviderController
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:03
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using PredatoryPlantsOnlineStore;
namespace PredatoryPlantsOnlineStore {
	public class ProviderController : BaseController {

		public ProviderController(){

		}

		~ProviderController(){

		}

		/// 
		/// <param name="obj"></param>
		public bool ProvideFlowerInfo(PredatoryPlant obj){

			return false;
		}

	}//end ProviderController

}//end namespace PredatoryPlantsOnlineStore