///////////////////////////////////////////////////////////
//  UserController.cs
//  Implementation of the Class UserController
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 13:37:01
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using PredatoryPlantsOnlineStore;
namespace PredatoryPlantsOnlineStore {
	public class UserController : BaseController {

		public UserController(){

		}

		~UserController(){

		}

		/// 
		/// <param name="id_product"></param>
		public void AddFlowerToCart(int id_product){

		}

		public void SignOut(){

		}

		public void ViewCart(){

		}

		public void ViewCatalogue(){

		}

		public void ViewPaymentInfo(){

		}

		/// 
		/// <param name="id_product"></param>
		public void ViewPredatoryPlantInfo(int id_product){

		}

	}//end UserController

}//end namespace PredatoryPlantsOnlineStore